# 自定义异常

1. 创建自定义异常类

        public class MyException extends Exception{
            private  String message;
            public MyException(String message){
                this.message=message;
            }
            public String getMessage(){
                return message;
            }
        }

2. 在方法中通过`throw`关键字抛出异常对象
3. 如果在当前抛出异常的方法中处理异常，可以使用try-catch语句捕获并处理，否则在方法的声明处通过throws关键字指明要抛出给方法调用者的异常，继续进行下一步操作。
4. 在出现异常方法的调用者中捕获并处理异常

示例：

        import java.util.Scanner;

    public class TestComputer {
        public static void main(String[] args) throws InstantiationException, IllegalAccessException {
            System.out.println("---------请输入两个数字:------");
            Scanner cin=new Scanner(System.in);
            int x=cin.nextInt();
            int y=cin.nextInt();
            Computer Cop=new Computer();
            try {
                Cop.CheckNumber(x, y);
            } catch (MyException e) {
                System.out.println(e.getMessage());
                e.printStackTrace();
            }
        }
    }
    class Computer {
        //定义方法，抛出异常
        public static void CheckNumber(int m, int n) throws MyException {
            if (m < 0 || n < 0) {
                throw new MyException("您传入要计算最大公约数的数字不合法,请仔细检查!");
            } else {
                while (m % n != 0) {
                    int temp = m % n;
                    m = n;
                    n = temp;
                }
            }
            System.err.println("计算的两个数的最大公约数为:" + n);
        }
    }